name: Terraform Apply
description: Setup and Apply Terraform Description

inputs:
  aws-access-key-id:
    description: AWS Access Key ID
    required: true
  aws-secret-access-key:
    description: AWS Secret Access Key
    required: true
  terraform-version:
    description: Terraform Version
    required: false
    default: '1.11.0'
  environment:
    description: Terraform environment
    required: true
  terraform-variables:
    description: Terraform Variables
    required: false
    default: ''

runs:
  using: composite

  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: eu-south-2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}

    - name: Terraform Init
      working-directory: terraform/env/${{ inputs.environment }}
      shell: bash
      run: terraform init

    - name: Terraform Plan
      working-directory: terraform/env/${{ inputs.environment }}
      shell: bash
      run: terraform plan -input=false -out=plan ${{ inputs.terraform-variables }}

    - name: Terraform Apply
      working-directory: terraform/env/${{ inputs.environment }}
      shell: bash
      run: terraform apply -auto-approve plan
